version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: phonepe-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: phonepe-backend
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: phonepe-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
